#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH --ntasks-per-node=48
#SBATCH -c 4
#SBATCH -N 1
#SBATCH -J openclosed
#SBATCH --account=hpc-prf-rqsued
#SBATCH -p normal
##SBATCH -q express

module reset
module load phys/BAGEL/master-foss-2023a

export BAGEL_NUM_THREADS=${SLURM_CPUS_PER_TASK}
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

srun BAGEL dysonplot.json
