#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH --ntasks-per-node=8
#SBATCH -c 24
#SBATCH -N 1
#SBATCH -J open
#SBATCH --account=hpc-prf-rqsued
#SBATCH -p normal
##SBATCH -q express

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PLACES=cores
export OMP_PROC_BIND=true

module reset
module load chem/CP2K/2025.2-foss-2025a-gcc-openmpi-aocl

export CP2K_PATH=/pc2/groups/hpc-prf-metdyn/metdyn02_Remi/cp2k_Otus/01_CP2K/cp2k
#source ${CP2K_PATH}/tools/toolchain/install/setup


rm cp2k.out
srun ${CP2K_PATH}/exe/local/cp2k.psmp GW.inp >> cp2k.out
